language: c

jobs:
  include:
    - os: linux
      dist: bionic
      arch: amd64


before_install: bundle install
script: rake
deploy:
  provider: releases
  token: ${token}
  file: mini-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    tags: true