language: c

jobs:
  include:
    - os: linux
      dist: bionic
      arch: amd64
    - os: windows
      arch: amd64

before_install: 
  - choco install mingw
  - choco install msys2
  - ridk.cmd exec pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain
  - ridk enable
  - bundle install

script: rake

deploy:
  provider: releases
  token: ${token}
  file: mini-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    tags: true